### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by zh8008** [ZengJiaxiong/Phosphorus-cycling-database#1]
According to the description of your Python script, your database seems to miss several files, such as "id2genemap. txt".Could you upload these necessary files？

**Comment by ZengJiaxiong** [comment]
Hello

You can find 'id2genemap.txt' file from release. https://github.com/ZengJiaxiong/Phosphorus-cycling-database/releases

**Comment by ZengJiaxiong** [comment]
By the way, you need to modified the path of id2genemap in all python script. For example, assuming you have download this file and the path for id2genemap file is '/usr/bin/id2genemap.txt'. then you need to revise line 10 in filter_Generate_ORF2gene.py. In this case, the new code in line 10 should be 'with open ('/usr/bin/id2genemap.txt','r') as IDfile:'
