### ISSUE TITLE
Excessive number of P gene copy numbers in genome analysis

### ISSUE THREAD

**Issue by rgtaketani** [ZengJiaxiong/Phosphorus-cycling-database#10]
Hi Jiaxiong,

I'm trying to use this program to annotate P cycle genes in genomes. We are noticing that the copy numbers are very high—hundreds of copies of some of them. The pipeline I am using is this. 
1- Extract AA sequences for ORFs with prodigal
2- Search PCycDB using diamond's blastp
3- Run filter_Generate_ORF2gene.py -s 95 -cov 200 -hit 0 

But the ORF2Pgene.txt fike has more than 745 matches. 

Thanks 
Rodrigo

**Comment by ZengJiaxiong** [comment]
Hi Rodrigo,

Something must be wrong when you running the filter_Generate_ORF2Gene.py. Many genes should be filtered at 95% identity. Please check whether the blastp output file is the same as the example file (S0028.PCycDB.blastp) list in "[Phosphorus-cycling-database](https://github.com/ZengJiaxiong/Phosphorus-cycling-database)/example file/". Moreover, the range of the "cov" is 0-100. A similar question is "https://github.com/ZengJiaxiong/Phosphorus-cycling-database/issues/2".

Thanks,
Jiaxiong

**Comment by rgtaketani** [comment]
Hi Jiaxiong,

Thanks for the reply. I changed the -cov to 100 (I imagine it is 100% coverage) just to test. I'm still getting >700 matches. The output of blastp is similar to the required. See head output below
```
NODE_1_1	132113.XP_003493950.1	40.3	568	323	6	59	611	346	912	1.45e-132	429
NODE_1_1	667015.Bacsa_1389	28.6	604	375	14	28	607	6	577	1.24e-67	235
NODE_1_1	bsa:Bacsa_1389	28.6	604	375	14	28	607	6	577	1.24e-67	235
NODE_1_2	1280706.AUJE01000013_gene1747	23.8	248	180	4	26	273	9	247	5.64e-13	72.4
NODE_1_2	1133850.SHJG_8860	23.9	230	171	2	23	250	8	235	3.93e-12	70.1
NODE_1_2	1120985.AUMI01000011_gene257	28.2	177	126	1	33	209	15	190	3.09e-11	67.4
NODE_1_2	1206101.AZXC01000014_gene741	29.6	135	87	3	18	148	3	133	7.10e-08	55.5
NODE_1_2	883156.HMPREF9282_01445	42.4	59	34	0	21	79	3	61	1.06e-06	49.7
NODE_1_2	591001.Acfer_1748	31.6	136	76	4	29	156	11	137	1.45e-06	53.5
NODE_1_2	1121935.AQXX01000111_gene5821	39.4	66	40	0	17	82	5	70	6.42e-04	45.4
```

Is there something else I can test?

EDIT: I just noticed that my output is one column shorter can this be the problem?

Thanks
Rodrigo

**Comment by ZengJiaxiong** [comment]
Hi Rodrigo,

Ah...I finally know why you got such a lot number of PCGs. Can you notice that NODE_1_1 was annotated to more than one gene (first three rows)? Therefore, the blastp command you used should be modified. Please add an additional parameter when you perform blastp search using diamond, that is, -k 1. This option would export the best matching gene (the first row).

Best wishes,
Jiaxiong

**Comment by ZengJiaxiong** [comment]
By the way, your output is the default output format, so you can use "python filter_Generate_ORF2gene.py -s 70 -cov 25 -hit 0 -blast your_file". The -cov here was inferred to hit-length because of the default output format.
The cutoff of 70 identity and 25 hit-length are suggested to annotated genomes, but it will filter some true positive genes. So you can also try "python filter_Generate_ORF2gene.py -s 30 -cov 25 -hit 0 -blast your_file" to obtain more potential PCGs.
The cutoff of coverage was not investigated in this paper.

**Comment by rgtaketani** [comment]
Jiaxiong,

The -k 1 did the trick now I have a reasonable number of hits. Initially I used -s 30 -cov 25 as suggested but increased it to test. 

Thanks for the help.
Regards
Rodrigo
