### ISSUE TITLE
Command issues

### ISSUE THREAD

**Issue by zh8008** [ZengJiaxiong/Phosphorus-cycling-database#2]
Hello, I have two questions:
1.What do you recommend setting the "-cov" and "-coverage" parameter?
2.How to adjust “filter_Generate_ORF2gene.py” script parameters if the comparison results of usearch was used?

**Comment by ZengJiaxiong** [comment]
Hi
I did not determine the accuracy under different alignment coverage. By defalut, the tabular result of DIAMOND or BLASTP should not include the alignment coverage. The first, second, third and fourth column should be query id, subject id, identity and hit-length. So you can use “filter_Generate_ORF2gene.py” script with following command: python filter_Generate_ORF2gene.py -s $identity -cov $hit-length -hit 0 -b $Sample.P.blast, where -cov in this case should be the hit-length and -hit should be mismatches.

I don't know what tabluar result of usearch looks like. I suggest to use  awk tool in Linux by typing "awk '$column_of_identify >=30 && $column_of_hit_length >=25' usearch.result". The column_of_identity and  column_of_hit_length should be numerical and match to you usearch result.
