### ISSUE TITLE
How to install the PCycDB?

### ISSUE THREAD

**Issue by B-1991-ing** [ZengJiaxiong/Phosphorus-cycling-database#3]
Dear PCycDB support team, 

Where is the installation instruction page for the PCycDB?

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Dear user,

You don't need to install it. Just download PCycDB and mapfile from this page, https://github.com/ZengJiaxiong/Phosphorus-cycling-database/releases, and then use diamond or blast. Please keep in mind that you need to prepare the binary file using diamond or blast, so that you can search your sequences against PCycDB.

Best wishes,

Jiaxiong

**Comment by B-1991-ing** [comment]
Hi Jiaxiong,

Sorry for the late reply.

Before preparing my *.blastp and quant.sf files, I have two questions.

**Question1:**
"**Please keep in mind that you need to prepare the binary file using diamond or blast, so that you can search your sequences against PCycDB.**"
Here, you mean firstly use my MAG file to blast the "**PCycDBv1.1.faa**" to generate the  binary file?

**Question2:**
"**Note that the fourth column is the 'query coverage', and DIAMOND or BLAST will not give this value by default.**" - You mean that we need to specify the first 4 columns of the blastp output format as **query id, subject id, identity and hit-length, query coverage**.
I am used to use diamond blastp, so it would be 
DB=PCycDBv1.1.faa
query=MAG.fa
diamond blastp --db ${DB} --query ${query} --very-sensitive --evalue 1e-10 --id 30 --out 
*.dmnd.out --outfmt 6 **qseqid sseqid pident length** qlen slen qstart qend qseq sseq evalue bitscore --max-target-seqs 1 --threads 30

Thank you very much.

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

The fasta format file (i.e., PCycDBv1.1.faa) is not readable for DIAMOND. You can prepare the binary file by typing the following command: diamond makedb --in PCycDBv1.1.faa -d PCycDB. The parament -d means the DB name you prefered. Then the DIAMOND will generate a file named PCycDB.dmnd, which is readable for DIAMOND.

If you want to identify PCGs from MAGs, first you should predict the Open Reading Frames from MAGs using other softwares, such as Prodigal which could be easily installed via conda. Then search PCycDB using DIAMOND. For details of Prodigal and DIAMOND, please search them in GOOGLE. 
DB=PCycDB.dmnd
query=MAGs.pro.fa
diamond blastp -e <e-value> -k <maximum number of target sequences to report alignments for> -p <threads> -d DB -q MAGs.pro.fa -f 6 qseqid sseqid pident qcovhsp length mismatch gapopen qstart qend sstart send evalue bitscore -o MAG.pro.PCycDB.blastp

Regards,

Jiaxiong

**Comment by B-1991-ing** [comment]
Hi Jiaxiong,

Thank you very much for your reply.

I exactly have the prodigal predicted MAG *.fa and *.faa files now. 

Next, I need to index and quantify the prodigal predicted MAG *.faa files acrosss all samples using the the Salmon software?

Could you give me some example command lines one how to run the Salmon quantification?
 
Best,

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

please refer https://github.com/COMBINE-lab/salmon for more detals.

Thanks,

Jiaxiong

**Comment by B-1991-ing** [comment]
Hi Jiaxiong, 

Thank you for the reference. I will have a look on that .

Best,

Bing

**Comment by brilliant2643** [comment]
> Hi Bing,
> 
> please refer https://github.com/COMBINE-lab/salmon for more detals.
> 
> Thanks,
> 
> Jiaxiong

Hi! I'm using PCycDB too, and I wonder what command you use in Salmon? I noticed that Salmon was for RNA-seq files, and my MAGs are from metagenome samples, so I really confuse about how to use salmon to count my data.
Looking forward to your reply! 

Best,
Sushi
