### ISSUE TITLE
example of checkm TPM output file 

### ISSUE THREAD

**Issue by u15412611** [ZengJiaxiong/Phosphorus-cycling-database#4]
Hi 
Thank you very much for a nice P-database
I would like to get an example of the checkm coverage values (TPM) .tsv files. 
I have obtained one but my Coverage_get.py analysis fails.

**Comment by ZengJiaxiong** [comment]
Hello,

A step by step tutorial has been added in this folder: example file.

Hope it can help you.

Best wishes,

Jiaxiong
