### ISSUE TITLE
Empty quant.sf

### ISSUE THREAD

**Issue by B-1991-ing** [ZengJiaxiong/Phosphorus-cycling-database#6]
Hi Jiaxiong,

I got empty quant.sf file as shown below. Have you ever met the similar condition as mine? 
<img width="1250" alt="Screenshot 2022-07-25 at 06 14 40" src="https://user-images.githubusercontent.com/54441633/180697662-2248c87d-13fb-4f35-a60a-76d16454d6bb.png">

My shell script,
[quant_sf_marinelake.txt](https://github.com/ZengJiaxiong/Phosphorus-cycling-database/files/9180154/quant_sf_marinelake.txt)

My log screenshot,
<img width="1373" alt="Screenshot 2022-07-25 at 12 06 27" src="https://user-images.githubusercontent.com/54441633/180752407-d0adabc5-4e64-4df9-b939-b323b2555c88.png">

Best,

Bing

**Comment by B-1991-ing** [comment]
Hi Jiaxiong,

I am wondering that can I use the salmon to quantify my **MAGs (*.faa protein sequences predicted by prodigal)** in **my *.fq.gz (metagenome sequences sequenced by the BGI)**? I don't have metatranscriptome data.

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

I never set docoy during quantification. Try to make index again without setting -d parament.

If you want to quantify the abundance of MAGs from metagenome dataset, I suggest to use CoverM, which could be found in GOOGLE/Github. It's a useful and easy tool to quantify both ORFs and MAGs from metagenome sequences. So, if there were other problems using salmon to quantify the abundance of ORFs, you can also try to quantify them by CoverM.

The usage of CoverM could be found in https://github.com/wwood/CoverM.

Kind regards,

Jiaxiong

**Comment by B-1991-ing** [comment]
Hi Jiaxiong,

Thank you for your suggestion, I am actually used to quantify my MAGs in the *.fq.gz by the CoverM. 

If I use CoverM, I won't have the same format as **quant.sf**. 

Then, could I still take my **XXXX_coverm_TPM.tsv** as the input of the parameter of **-t**, as shown in the command line below ?

python Coverage_get.py -i XXXXORF2Pgene.txt -t **XXXX_coverm_TPM.tsv** -o XXXX.TPM.txt

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

I don't remember which column of the output generated by CoverM is the abundance. In quant.sf, which produced by Salmon, the fourth column is TPM (abundance), therefore, the 13th row in Coverage.py is defined as "orf2cov[orf.split('\t')[0]]=orf.split('\t')[3]".  orf2cov[orf.split('\t')[0]] (1-1) tell the program that the fisrt column is ORF name  and orf2cov[orf.split('\t')[3]] (4-1) tell the program the fourth column is the TPM.
Therefore, if the second column of the output generated by CoverM is the abundance, we should modify the 13th row of this script to "orf2cov[orf.split('\t')[0]]=orf.split('\t')[1]", and then you can use this script to calculate the abundance of PCGs.

Best wishes,

Jiaxiong

**Comment by B-1991-ing** [comment]
Jiaxiong,

Although I got the TPM.tsv file for each sample, I am quite confused by another question that whether I can directly focus on my assembled MAGs or I must look at the sample-wise level?

Before what I thought is that I need to get the **MAG.P.blast** and the **MAG.TPM.txt**. But, in the user guide, you gave one example at the sample level - **Sample.P.blast** and **Sample.TPM.txt**. 

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

The script described in this paper is designed for fast analysis of different phosphorus cycling genes from metagenome sequencing dataset. This means that you can profile the PCG abundance at ORFs-level from the whole community, but not those PCGs predicted from MAGs.

If you want to know the abundance of MAGs carrying speicific PCG, I suggest to quantify them at sample level (i.e., directly quantify MAGs from clean reads using CoverM) instead of quantifying the predicted ORFs of MAGs aganist clean reads. This is because different MAGs can carry PCGs with the same sequence (or with high similarity), which might result in a unexpected high abundance of predited ORFs of MAGs.

Kind regards,

Jiaxiong

**Comment by B-1991-ing** [comment]
Hi Jiiaxiong,

So, I firstly did the diamond blastp for my prodigal-predicted MAGs, to predict the phosphorus cycling genes. Then, quantify the assembled MAGs *fna across each sample. If I only want to focus on the MAGs' phosphorus pathway?

Will we get some figures based on the PCyCDB results? Or what kind of figure can I make based on my case?

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Bing,

You can reconstruct the phosphorus pathway based on PCG annotation according to Fig. 2 in this paper. Besides, you can also search the MAG-ORFs against KEGG to reconstruct more metabolic pathway.

Thanks,

Jiaxiong

**Comment by B-1991-ing** [comment]
Thank you for your reply Jiaxiong. But I need to make the figure manually?

**Comment by B-1991-ing** [comment]
Jiaxiong,

In the readme.txt, how could we get the quant.sf. ?

<img width="1332" alt="Screenshot 2022-07-28 at 21 58 43" src="https://user-images.githubusercontent.com/54441633/181626435-f34bb0dc-5fe3-4181-ab66-d3120759162a.png">

For the CoverM, I can only get the TPM value for each MAG instead for each contig of each MAG. So I think I need to use the salmon to get the quant.sf..

Best,

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

You need prepare the figure using Photoshop or AI...

With CoverM, you can obtain the abundance matrix result using Metaphlan2's script.

Thanks,

Jiaxiong

**Comment by B-1991-ing** [comment]
Jiaxiong,

I think I can't get the TPM value for each contig of each MAG, something like below.
**Name	Length	EffectiveLength	TPM	NumReads
k141_433371_length_91162_cov_12.3664_1	90	8.026	0.000000	0.000**

Now, I already got the blastp for each MAG, and got the Pgene.txt for each MAG blastp. Then, **cat *Pgene.txt >> ${Pgene_txt}** to concatenate all ORF2gene.txt into one gene.txt.
Command line:
python filter_Generate_ORF2gene.py -s 30 -cov 0 -hit 25 -blast ${file}
cat *Pgene.txt >> ${Pgene_txt}

Next, I quantified all MAGs using all metagenome samples, and got one quant.sf and one *TPM.txt for each sample. 
Command line:
python Coverage_get.py -i ${Pgene_txt} -t ${quant_sf} -o ${i}.TPM.txt

Finally, concatenated all *.TPM.txt of all samples into one all.result.TPM.txt.
Command line:
python merge_metaphlan_tables.py *.TPM.txt > ${quant_sf_batch}all.result.TPM.txt

Bing

**Comment by B-1991-ing** [comment]
Hi Jiaxiong,

I am wondering that how do people get the quant.sf for each metagenome sample file usually?

Bing

**Comment by ZengJiaxiong** [comment]
Hi Bing,

'quant.sf' is the result produced by Salmon, and we usually use Salmon to quantify the ORFs predicted from assembled contigs.

Best wishes,

Jiaxiong
