### ISSUE TITLE
Could you please release the protein fasta file for the Pcycdb, thanks very much

### ISSUE THREAD

**Issue by Jadedragonn** [ZengJiaxiong/Phosphorus-cycling-database#7]
The article said "The NCBI RefSeq database was employed to improve the comprehensiveness and integrality by searching against the developed PCycDB using USEARCH v.11.0 with an 80% global identity", but we didn't see the protein fasta file. Could you please release the protein fasta file for the Pcycdb, thanks very much!

**Comment by ZengJiaxiong** [comment]
Hi,


You can download the RefSeq database via NCBI ftp server.


The PCGs identified from RefSeq database have been included in PCycDB.faa, you can find them in id2gene.txt file by searching "NCBI".


Thanks
Jiaxiong



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 8, 2022 22:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ZengJiaxiong/Phosphorus-cycling-database] Could you please releasethe protein fasta file for the Pcycdb, thanks very much (Issue #7)




 
The article said "The NCBI RefSeq database was employed to improve the comprehensiveness and integrality by searching against the developed PCycDB using USEARCH v.11.0 with an 80% global identity", but we didn't see the protein fasta file. Could you please release the protein fasta file for the Pcycdb, thanks very much!

**Comment by Jadedragonn** [comment]
Hi Jiaxiong,

The article said "The NCBI RefSeq database (ftp://ftp.ncbi.nlm.nih.gov/refseq/release/, downloaded on Oct. 2, 2021) was employed to improve the comprehensiveness and integrality by searching against the **_developed PCycDB_** using USEARCH v.11.0 with an 80% global identity. It should be noted that a strict cutoff (i.e., 80%) was applied in this step because of a large number of sequences in the NCBI RefSeq database. All amino acid representative sequences and nontarget homologues were de-duplicated and clustered by CD-HIT at 100% identity. Finally, all representative sequences and homologues were selected to construct PCycDB".  

Did you mean that you generated the amino acid sequences of PCycDB.faa using **_developed PCycDB_** to search against the Nr database and then de-duplicated and clustered by CD-HIT at 100% identity?

Besides, were the "pafAORF.nuc.fa" and "S0028ORF2Pgene.txt" in your attached files as "PCycDB.faa" and "id2gene.txt" file?

Best wishes,

Jade

**Comment by ZengJiaxiong** [comment]
Hi Jade,

The final database, PCycDB.faa, was generated after integrating arCOG, COG, eggNOG, KEGG and NCBI RefSeq databases. It's a curated sequence collection.

"pafAORF.nuc.fa" is the sequences extracted from metagenome and "S0028ORF2Pgene.txt" is a mapping file for extraction. You can download PCycDB.faa and id2gene.txt from here: https://github.com/ZengJiaxiong/Phosphorus-cycling-database/releases

Thanks,

Jiaxiong

**Comment by Jadedragonn** [comment]
Thanks for your guide! We've got the database.
