### ISSUE TITLE
set up question

### ISSUE THREAD

**Issue by DrRumble** [ZengJiaxiong/Phosphorus-cycling-database#8]
Hi, 
I recently came across this database, however I am also pretty new to bioinformatics and I am used to seeing publications like these as a kind of package to download but I see that is not the case for this. 

Is there a set of packages or programs I need to use this database? How do I get this set up for my computer?

**Comment by DrRumble** [comment]
P.S. Does the alignment file have to be a blastp file from blast+ or DIAMOND? I have been using bbmap since I have data from soil microbiomes and those produce BAM, covstats.txt, and rpkmstats.txt files. the directions are a bit vague to me but I am still developing an eye for this work.

**Comment by DrRumble** [comment]
Nevermind, I am a greenhorn but I figured it out XD 
Thanks!

**Comment by ZengJiaxiong** [comment]
Hi,

Sorry for being late to reply to you. PCycDB.faa is a protein sequence file. The only thing you need to do is downloading PCycDB.faa and installing blast+ or diamond program. The database readable for blast+ or diamond can be constructed by typing 'makeblastdb' or 'diamond makedb'.
bbmap could also be used to align the query sequence against PCycDB. But you might need additional method to calculate the abundance of PCGs.

Thanks,
Jiaxiong
