### ISSUE TITLE
Clarification on input requirements and output files

### ISSUE THREAD

**Issue by gabrielrocha1** [ZengJiaxiong/Phosphorus-cycling-database#9]
Dear PCycDB developer,

I would like to clarify whether the input .fasta file for PCycDB analysis should be based on contigs or can it also be read-based? I am confused about the quant.sf file and would appreciate some guidance on this matter.

Thank you for your help.

**Comment by ZengJiaxiong** [comment]
Hi,

PCycDB could also be used based on reads, but other quantification methods like RPKM should be used. Please refer to "https://github.com/xinehc/args_oap", which is a easy-to-use program.

Best wishes,
Jiaxiong
